// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTyzz_Otws_I-UzXkI-YH7QzmxGymLhs',
    appId: '1:526185856516:web:e65cfc9fe572183f0cbf51',
    messagingSenderId: '526185856516',
    projectId: 'mealmommyapplication',
    authDomain: 'mealmommyapplication.firebaseapp.com',
    storageBucket: 'mealmommyapplication.firebasestorage.app',
    measurementId: 'G-G3RBHPQX0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiUjGqos6dxDMxeaUAePje47u9n0-8jFI',
    appId: '1:526185856516:android:6339f3fe8f229dd50cbf51',
    messagingSenderId: '526185856516',
    projectId: 'mealmommyapplication',
    storageBucket: 'mealmommyapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZZP_j8JPi_67KnSB7i3SA1bTtFeHzFO8',
    appId: '1:526185856516:ios:5fe890c5acb114cd0cbf51',
    messagingSenderId: '526185856516',
    projectId: 'mealmommyapplication',
    storageBucket: 'mealmommyapplication.firebasestorage.app',
    iosBundleId: 'com.example.mealmommyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZZP_j8JPi_67KnSB7i3SA1bTtFeHzFO8',
    appId: '1:526185856516:ios:5fe890c5acb114cd0cbf51',
    messagingSenderId: '526185856516',
    projectId: 'mealmommyapplication',
    storageBucket: 'mealmommyapplication.firebasestorage.app',
    iosBundleId: 'com.example.mealmommyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoTyzz_Otws_I-UzXkI-YH7QzmxGymLhs',
    appId: '1:526185856516:web:5423601860fe926a0cbf51',
    messagingSenderId: '526185856516',
    projectId: 'mealmommyapplication',
    authDomain: 'mealmommyapplication.firebaseapp.com',
    storageBucket: 'mealmommyapplication.firebasestorage.app',
    measurementId: 'G-Y9TCE8FCPJ',
  );

}